---
Logging:
  IncludeScopes: false
  Debug:
    LogLevel:
      Default: Information
  Console:
    LogLevel:
      Default: Information

spring:
  cloud:
    config:
      validate_certificates: false
